{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.triumphteam",
    "module": "triumph-gui",
    "version": "3.1.3-COLLFIX",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "triumph-gui-3.1.3-COLLFIX.jar",
          "url": "triumph-gui-3.1.3-COLLFIX.jar",
          "size": 73290,
          "sha512": "8c83c50e7b8472bcc0e3fa321b102aff0426d727bda8eef655c0ed1913f4ac1817977428f2a1986e2cfc8cdf24970fc6816cc73b76f55983a951c4211ce0ff49",
          "sha256": "03227857b13733583b3f3f3083fad4f22e136d06c6bbc46dea1eca8a607ed143",
          "sha1": "22f91da96a8edc7432ec5333e13300042e910c98",
          "md5": "b4e8f250b3799e76bf2aa57430e18cca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "triumph-gui-3.1.3-COLLFIX.jar",
          "url": "triumph-gui-3.1.3-COLLFIX.jar",
          "size": 73290,
          "sha512": "8c83c50e7b8472bcc0e3fa321b102aff0426d727bda8eef655c0ed1913f4ac1817977428f2a1986e2cfc8cdf24970fc6816cc73b76f55983a951c4211ce0ff49",
          "sha256": "03227857b13733583b3f3f3083fad4f22e136d06c6bbc46dea1eca8a607ed143",
          "sha1": "22f91da96a8edc7432ec5333e13300042e910c98",
          "md5": "b4e8f250b3799e76bf2aa57430e18cca"
        }
      ]
    }
  ]
}
