mysql:
  host: localhost
  port: 3306
  database: plugins
  user: everything
  password: root

tasks:
  profile-update-frequency: 150 # in seconds
  update-frequency: 300 # in seconds
  time-check-frequency: 10 # in seconds
  texture-update-frequency: 600 # in seconds

messages:
  not-a-player: '&cOnly in-game players can use this command.'
  invalid-island: '&cYou must belong to an island to view the leaderboard.'

guis:
  # GUI options for the main menu gui. This gui will show all the different leaderboard
  # types such as your own island's leaderboard, all players, etc.
  menu:
    name: '&aSelect a Leaderboard'
    rows: 3
    items:
      own-island:
        material: DIAMOND_ORE
        data: 0
        name: '&aYour Island''s Leaderboard'
        lore:
          - '&fView a leaderboard of all statistics'
          - '&fbetween members of your Island'
        slot: 10
        action: OWN_ISLAND
      all-players:
        material: DIAMOND
        data: 0
        name: '&eAll Player Leaderboards'
        lore:
          - '&fView a leaderboard of all'
          - '&findividual player statistics'
        slot: 13
        action: ALL_PLAYERS
      all-islands:
        material: DIAMOND_BLOCK
        data: 0
        name: '&cAll Island Leaderboards'
        lore:
          - '&fView a leaderboard of all combined'
          - '&fstatistics for Islands ranked'
          - '&fagainst each other'
        slot: 16
        action: ALL_ISLANDS
  # GUI options for the Leaderboards main menu. This gui will show all the categories
  # you can view statistics from such as Time stats, Combat stats, etc.
  lb-menu:
    name: '&aStats Leaderboards'
    rows: 3
    items:
      time-stats:
        material: WATCH
        data: 0
        name: '&e&lTime Statistics'
        lore:
          - '&7Click here to view the Leaderboards'
          - '&7for Time statistics'
        slot: 10
        action: TIME
      combat-stats:
        material: DIAMOND_SWORD
        data: 0
        name: '&c&lCombat Statistics'
        lore:
          - '&7Click here to view the Leaderboards'
          - '&7for Combat statistics'
        slot: 12
        action: COMBAT
      block-stats:
        material: BEDROCK
        data: 0
        name: '&a&lBlock Statistics'
        lore:
          - '&7Click here to view the Leaderboards'
          - '&7for Block statistics'
        slot: 14
        action: BLOCK
      other-stats:
        material: BEACON
        data: 0
        name: '&d&lOther Statistics'
        lore:
          - '&7Click here to view the Leaderboards'
          - '&7for Other statistics'
        slot: 16
        action: OTHER
  # GUI options for the time leaderboard
  lb-time:
    name: '&aTime Leaderboards'
    rows: 3
    items:
      connected:
        material: COMPASS
        data: 0
        name: '&aTime Connected'
        lore: []
        slot: 11
        action: TIME_CONNECTED
      played:
        material: WATCH
        data: 0
        name: '&2Time Played'
        lore: []
        slot: 15
        action: TIME_PLAYED
  # GUI options for the combat leaderboard
  lb-combat:
    name: '&aCombat Leaderboards'
    rows: 3
    items:
      mob-kills:
        material: SKULL_ITEM
        data: 4
        name: '&dMob Kills'
        lore: []
        slot: 11
        action: MOB_KILLS
  # GUI options for the blocks leaderboard
  lb-block:
    name: '&aBlock Leaderboards'
    rows: 4
    items:
      blocks-broken:
        material: DIAMOND_PICKAXE
        data: 0
        name: '&3Blocks Broken'
        lore: []
        slot: 10
        action: BLOCKS_BROKEN
      blocks-travelled:
        material: DIAMOND_BOOTS
        data: 0
        name: '&aBlocks Travelled'
        lore: []
        slot: 12
        action: BLOCKS_TRAVELLED
      ores-mined:
        material: DIAMOND_ORE
        data: 0
        name: '&bOres Mined'
        lore: []
        slot: 14
        action: ORES_MINED
      wood-mined:
        material: LOG
        data: 0
        name: '&6Wood Mined'
        lore: []
        slot: 16
        action: WOOD_MINED
  lb-other:
    name: '&aOther Leaderboards'
    rows: 3
    items:

  leaderboard:
    name: '&aTop 9 %stat% %type%'
    rows: 5
    score-slot: 19

placeholder:
  limit: 9
  out-of-bounds: '&floading...'
  island:
    entry: '{leaderboards_island_%statistic%_%index%}'
    bad-island: 'NaI'
    format: '&3&l%index%. &r&f%island% - &b%value%'
  player:
    entry: '{leaderboards_player_%statistic%_%index%}'
    bad-player: 'NaP'
    format: '&3&l%index%. &r&f%player% - &b%value%'

items:
  index-to-block:
    1: DIAMOND_BLOCK:0
    2: EMERALD_BLOCK:0
    3: GOLD_BLOCK:0
    4: IRON_BLOCK:0
    5: DIAMOND_ORE:0
    6: EMERALD_ORE:0
    7: GOLD_ORE:0
    8: IRON_IRE:0
    9: REDSTONE_ORE:0
  own-score-block: BEACON:0
  island-entry:
    name: '&3&l#%index% &r&b- %name%'
    lore:
      - ''
      - '&f&lGroup Size: &r&a%size%'
      - '&f&lCurrent Total: &r&a%value%'
  player-entry:
    name: '&3&l#%index% &r&b- %name%'
    lore:
      - ''
      - '&f&lCurrent Total: &r&a%value%'