{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.triumphteam",
    "module": "triumph-gui",
    "version": "3.1.3-COLLFIX",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "triumph-gui-3.1.3-COLLFIX.jar",
          "url": "triumph-gui-3.1.3-COLLFIX.jar",
          "size": 72663,
          "sha512": "815c61d156d29b5f402587077a165dfa6a90f9639893be0afa8428dcbe3ee44ff27117a43ff7012563529c74108c722a46dc9fa1b8988070a5ce1a0b872210fd",
          "sha256": "afaa0575e3da4492bc8bd8ff3b9831727178e85ca8ef0b5cf16d6cc3e518f44f",
          "sha1": "dee83921064ffb676183cf50fe7c52b9bc285032",
          "md5": "ab3f1e0c6e1a3348c1b6f50b7d3d8ce4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "triumph-gui-3.1.3-COLLFIX.jar",
          "url": "triumph-gui-3.1.3-COLLFIX.jar",
          "size": 72663,
          "sha512": "815c61d156d29b5f402587077a165dfa6a90f9639893be0afa8428dcbe3ee44ff27117a43ff7012563529c74108c722a46dc9fa1b8988070a5ce1a0b872210fd",
          "sha256": "afaa0575e3da4492bc8bd8ff3b9831727178e85ca8ef0b5cf16d6cc3e518f44f",
          "sha1": "dee83921064ffb676183cf50fe7c52b9bc285032",
          "md5": "ab3f1e0c6e1a3348c1b6f50b7d3d8ce4"
        }
      ]
    }
  ]
}
